name: Cache Warm Up
on:
  workflow_call:
    inputs:
      asset_id:
        type: string
        required: true
jobs:
  cache-warm-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/github-script@v8
        env:
          ASSET_ID: ${{ inputs.asset_id }}
        with:
          github-token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          script: |
            const { default: run } = await import('${{ github.workspace }}/actions/cacheWarmUp/index.ts')
            return await run({ github })
