name: Cache Warm Up
on:
  workflow_call:
    inputs:
      asset_id:
        type: string
        required: true
jobs:
  cache-warm-up:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          ASSET_ID: ${{ inputs.asset_id }}
        run: |
          time gh api --header "Accept: application/octet-stream" \
            "/repos/zsideload/assets/releases/assets/$ASSET_ID" \
            > /dev/null
