name: iNKillerPlus1 fetch deb
on:
  workflow_dispatch:
jobs:
  fetch-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          script: |
            const { default: run } = await import('${{ github.workspace }}/actions/inkillerplus1/fetchDeb.ts')
            return await run({ github, context, core })
